version: "3"

networks:
  default:
    external: true
    name: lanet

services:
  {{.name}}:
    container_name: {{.name}}
    image: unitytechnologies/accelerator
    restart: always
    environment:
      TZ:
      USER:
      PASSWORD:
      DISABLE_USAGE_STATS:
    volumes:
    - {{host_ws}}/{{.name}}/agent:/agent
    dns:
    - {{guest_dns_ip}}
    networks:
      default:
        ipv4_address: {{.ip}}
    ports:
    - "{{.ports.acc.host}}:{{.ports.acc.guest}}"
    # - "{{.ports.web.host}}:{{.ports.web.guest}}"
