services:
  unity_2021_2_7f1_windows_mono_0_15_0:
    container_name: unity
    image: unityci/editor:ubuntu-2021.2.7f1-windows-mono-0.15.0
    restart: always
    environment:
    - TZ=Asia/Shanghai
    volumes:
    - /Users/hd/gameci:/gameci
    networks:
      default:
        ipv4_address: 192.168.1.8
    dns:
    - 192.168.1.2
    # command: bash
    # ports:
    # - "80:80"
    # - "443:443"
    # - "2233:2233"

networks:
  default:
    external: true
    name: lanet
