version: "3"

networks:
  default:
    external: true
    name: lanet

services:
  clash:
    container_name: clash
    image: dreamacro/clash:dev
    restart: always
    environment:
    - TZ=Asia/Shanghai
    volumes:
    - {{host_workspace}}/clash/config.yaml:/root/.config/clash/config.yaml
    - {{host_workspace}}/clash/ui:/ui
    dns:
    - {{guest_dns_ip}}
    networks:
      default:
        ipv4_address: {{guest_ip}}
    ports:
    # - "{{port_proxy_host}}:{{port_proxy_guest}}"
    # - "{{port_web_host}}:{{port_web_guest}}"
