networks:
  default:
    external: true
    name: lanet

services:
  {{.name}}:
    container_name: {{.name}}
    image: dreamacro/clash:dev
    restart: always
    environment:
      TZ:
    volumes:
    - {{host_ws}}/{{.name}}/config.yaml:/root/.config/clash/config.yaml
    - {{host_ws}}/{{.name}}/yacd/public:/ui
    dns:
    - {{guest_dns_ip}}
    networks:
      default:
        ipv4_address: {{.ip}}
    ports:
    - "{{.ports.proxy.host}}:{{.ports.proxy.guest}}"
    # - "{{.ports.web.host}}:{{.ports.web.guest}}"
