networks:
  default:
    external: true
    name: lanet

services:
  {{.name}}:
    container_name: {{.name}}
    image: sourcegraph/server:5.0.1
    restart: always
    user: 0:0
    environment:
      TZ:
      JAVA_OPTS:
    volumes:
    - {{host_ws}}/{{.name}}/config:/etc/sourcegraph
    - {{host_ws}}/{{.name}}/data:/var/opt/sourcegraph
    dns:
    - {{guest_dns_ip}}
    networks:
      default:
        ipv4_address: {{.ip}}
    # ports:
    # - "{{.ports.web.host}}:{{.ports.web.guest}}"
