version: "3"

services:
  drone_server:
    container_name: drone_server
    image: drone/drone
    restart: always
    environment:
    - DRONE_GITEA_SERVER=https://gitea.wolfired.com
    - DRONE_GITEA_CLIENT_ID=295ebfa9-3635-4bfc-8aa4-ac1abe7d383c
    - DRONE_GITEA_CLIENT_SECRET=FPbeSZD4UiojOQfwJevjt6c2CKG0KyngCYNs48HviauG
    - DRONE_SERVER_PROTO=https
    - DRONE_SERVER_HOST=drone.wolfired.com
    - DRONE_RPC_SECRET=83630ed531cc42a8ce6162f9a19bdeb0
    - DRONE_USER_CREATE=username:admin,machine:false,admin:true,token:5fad710ad2c2d89b1fa7ebd0165034a8
    volumes:
    - /Users/hd/drone:/data
    networks:
      default:
        ipv4_address: 192.168.1.5
    dns:
    - 192.168.1.2
    ports:
    - "4000:80"

  runner:
    container_name: drone_runner
    image: drone/drone-runner-docker
    restart: always
    environment:
    - DRONE_RPC_PROTO=https
    - DRONE_RPC_HOST=drone.wolfired.com
    - DRONE_RPC_SECRET=83630ed531cc42a8ce6162f9a19bdeb0
    - DRONE_RUNNER_CAPACITY=2
    - DRONE_RUNNER_NAME=runner1
    - DRONE_HTTP_PROTO=http
    - DRONE_HTTP_HOST=runner1.wolfired.com:4001
    - DRONE_HTTP_BIND=:4001
    - DRONE_UI_DISABLED=false
    - DRONE_UI_USERNAME=admin
    - DRONE_UI_PASSWORD=admin
    - DRONE_RUNNER_NETWORKS=lanet
    # - DRONE_MEMORY_LIMIT=8589934592
    # - DRONE_MEMORY_SWAP_LIMIT=8589934592
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        ipv4_address: 192.168.1.6
    dns:
    - 192.168.1.2
    ports:
    - "4001:4001"

networks:
  default:
    external: true
    name: lanet
