version: "3"

networks:
  default:
    external: true
    name: lanet

services:
  {{.name}}:
    container_name: {{.name}}
    image: drone/drone
    restart: always
    environment:
      TZ:
      DRONE_GITEA_SERVER:
      DRONE_GITEA_CLIENT_ID:
      DRONE_GITEA_CLIENT_SECRET:
      DRONE_SERVER_PROTO:
      DRONE_SERVER_HOST:
      DRONE_RPC_SECRET:
      DRONE_USER_CREATE:
    volumes:
    - {{host_ws}}/{{.name}}:/data
    dns:
    - {{guest_dns_ip}}
    networks:
      default:
        ipv4_address: {{.ip}}
    # ports:
    # - "{{.ports.web.host}}:{{.ports.web.guest}}"
