version: "3"

services:
  gitea:
    image: gitea/gitea
    container_name: gitea
    restart: always
    environment:
    - TZ=Asia/Shanghai
    volumes:
    - /Users/hd/gitea/data:/data
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    networks:
      default:
        ipv4_address: 192.168.1.4
    dns:
    - 192.168.1.2
    ports:
    - "3000:3000"
    - "22:22"

networks:
  default:
    external: true
    name: lanet
