version: "3"

networks:
  default:
    external: true
    name: lanet

services:
  gitea:
    image: gitea/gitea
    container_name: gitea
    restart: always
    environment:
      TZ:
    volumes:
    - {{host_workspace}}/gitea/data:/data
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    dns:
    - {{guest_dns_ip}}
    networks:
      default:
        ipv4_address: {{guest_ip}}
    ports:
    - "{{port_ssh_host}}:{{port_ssh_guest}}"
    # - "{{port_web_host}}:{{port_web_guest}}"
