version: "3"

networks:
  default:
    external: true
    name: lanet

services:
  {{.name}}:
    image: gitea/gitea
    container_name: {{.name}}
    restart: always
    environment:
      TZ:
    volumes:
    - {{host_ws}}/{{.name}}/data:/data
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    dns:
    - {{guest_dns_ip}}
    networks:
      default:
        ipv4_address: {{.ip}}
    ports:
    - "{{.ports.ssh.host}}:{{.ports.ssh.guest}}"
    # - "{{.ports.web.host}}:{{.ports.web.guest}}"
