version: "3"

networks:
  default:
    external: true
    name: lanet

services:
  coredns:
    container_name: coredns
    image: coredns/coredns:latest
    restart: always
    environment:
      TZ:
    command: -conf /cfgs/Corefile
    volumes:
    - {{host_workspace}}/coredns/cfgs:/cfgs
    - {{host_workspace}}/coredns/zones:/zones
    networks:
      default:
        ipv4_address: {{guest_ip}}
    ports:
    - "{{host_ip}}:{{port_udp_host}}:{{port_udp_guest}}/udp"
    - "{{host_ip}}:{{port_tcp_host}}:{{port_tcp_guest}}/tcp"
    # - "{{host_ip}}:{{port_health_host}}:{{port_health_guest}}"
