networks:
  default:
    external: true
    name: lanet

services:
  {{.name}}:
    container_name: {{.name}}
    image: coredns/coredns:latest
    restart: always
    environment:
      TZ:
    command: -conf /cfgs/Corefile
    volumes:
    - {{host_ws}}/{{.name}}/cfgs:/cfgs
    - {{host_ws}}/{{.name}}/zones:/zones
    networks:
      default:
        ipv4_address: {{.ip}}
    ports:
    - "{{host_ip}}:{{.ports.udp.host}}:{{.ports.udp.guest}}/udp"
    - "{{host_ip}}:{{.ports.udp.host}}:{{.ports.tcp.guest}}/tcp"
    # - "{{host_ip}}:{{.ports.health.host}}:{{.ports.health.guest}}"
