version: "3"

networks:
  default:
    external: true
    name: lanet

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    volumes:
    - {{host_workspace}}/nginx/html:/usr/share/nginx/html:ro
    - {{host_workspace}}/nginx/conf:/etc/nginx:ro
    dns:
    - {{guest_dns_ip}}
    networks:
      default:
        ipv4_address: {{guest_ip}}
    ports:
    - "{{port_web_host}}:{{port_web_guest}}"
    - "{{port_ssl_host}}:{{port_ssl_guest}}"
