version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    environment:
    - TZ=Asia/Shanghai
    volumes:
    - /Users/hd/nginx/html:/usr/share/nginx/html:ro
    - /Users/hd/nginx/conf:/etc/nginx:ro
    networks:
      default:
        ipv4_address: 192.168.1.3
    dns:
    - 192.168.1.2
    ports:
    - "80:80"
    - "443:443"
    - "2233:2233"

networks:
  default:
    external: true
    name: lanet

