networks:
  default:
    external: true
    name: lanet

services:
  {{.name}}:
    container_name: {{.name}}
    image: nginx
    restart: always
    environment:
      TZ:
    volumes:
    - {{host_ws}}/{{.name}}/html:/usr/share/nginx/html
    - {{host_ws}}/{{.name}}/conf:/etc/nginx:ro
    dns:
    - {{guest_dns_ip}}
    networks:
      default:
        ipv4_address: {{.ip}}
    ports:
    - "{{.ports.http.host}}:{{.ports.http.guest}}"
    - "{{.ports.https.host}}:{{.ports.https.guest}}"
