version: "3"

networks:
  default:
    external: true
    name: lanet

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:latest
    restart: always
    environment:
    - TZ=Asia/Shanghai
    - JAVA_OPTS='-Duser.timezone=Asia/Shanghai'
    volumes:
    - {{host_workspace}}/jenkins/data:/var/jenkins_home
    dns:
    - {{guest_dns_ip}}
    networks:
      default:
        ipv4_address: {{guest_ip}}
    ports:
    - "58080:8080"
    - "50000:50000"
