version: "3"

networks:
  default:
    external: true
    name: lanet

services:
  {{.name}}:
    container_name: {{.name}}
    image: jenkins/jenkins:latest
    restart: always
    environment:
      TZ:
      JAVA_OPTS:
    volumes:
    - {{host_ws}}/{{.name}}/data:/var/jenkins_home
    dns:
    - {{guest_dns_ip}}
    networks:
      default:
        ipv4_address: {{.ip}}
    ports:
    - "{{.ports.agent.host}}:{{.ports.agent.guest}}"
    # - "{{.ports.web.host}}:{{.ports.web.guest}}"
